# Generated by Django 3.1.1 on 2021-05-26 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products_all',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=30)),
                ('product_price', models.IntegerField(default=0)),
                ('price_date', models.DateTimeField(verbose_name='updated on')),
                ('product_picture2', models.FilePathField(path='/images')),
            ],
        ),
    ]
