# Generated by Django 3.1.1 on 2021-03-01 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=30)),
                ('product_description', models.CharField(max_length=200)),
                ('product_banner', models.FilePathField(path='/produce/images/')),
            ],
        ),
        migrations.CreateModel(
            name='Product_types',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(max_length=20)),
                ('product_origin', models.CharField(max_length=30)),
                ('product_grade', models.CharField(max_length=10)),
                ('product_picture', models.FilePathField(path='/produce/images/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produce.product')),
            ],
        ),
    ]
