# Generated by Django 3.1.1 on 2021-04-15 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salt_class', models.CharField(max_length=30)),
                ('salt_description', models.CharField(max_length=200)),
                ('salt_banner', models.FilePathField(path='/produce/images/')),
                ('salt_thumbnail', models.FilePathField(path='/produce/images/')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='product_thumbnail',
            field=models.FilePathField(default=None, path='/produce/images/'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Salt_products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salt_type', models.CharField(max_length=30)),
                ('salt_origin', models.CharField(max_length=20)),
                ('salt_type_picture', models.FilePathField(path='/produce/images/')),
                ('salt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produce.salt')),
            ],
        ),
    ]
