# Generated by Django 3.1.1 on 2021-04-15 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produce', '0002_auto_20210415_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meat_animal', models.CharField(max_length=30)),
                ('meat_description', models.CharField(max_length=200)),
                ('meat_banner', models.FilePathField(path='/produce/images/')),
                ('meat_thumbnail', models.FilePathField(path='/produce/images/')),
            ],
        ),
        migrations.CreateModel(
            name='Meat_products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meat_type', models.CharField(max_length=30)),
                ('meat_type_picture', models.FilePathField(path='/produce/images/')),
                ('meat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produce.meat')),
            ],
        ),
    ]
