# Generated by Django 3.1.1 on 2021-04-16 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produce', '0003_meat_meat_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pulses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pulses_name', models.CharField(max_length=30)),
                ('pulses_description', models.CharField(max_length=200)),
                ('pulses_banner', models.FilePathField(path='/produce/images/')),
                ('pulses_thumbnail', models.FilePathField(path='/produce/images/')),
            ],
        ),
        migrations.CreateModel(
            name='Pulses_products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pulses_type', models.CharField(max_length=30)),
                ('pulses_type_picture', models.FilePathField(path='/produce/images/')),
                ('pulses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produce.pulses')),
            ],
        ),
    ]
